=== LilDev1l/java_4semestr/lab4/files/xmlSchema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="number" type="xs:int"/>
  <xs:element name="type" type="xs:string"/>
  <xs:element name="Card">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="number"/>
        <xs:element ref="type"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Cards">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Card" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Account">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="number"/>
        <xs:element ref="Cards"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Accounts">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Account" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== LilDev1l/java_4semestr/lab4/files/accounts.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Accounts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="xmlSchema.xsd">
    <Account>
        <number>1</number>
        <Cards>
            <Card>
                <number>42550</number>
                <type>debit</type>
            </Card>
            <Card>
                <number>42551</number>
                <type>credit</type>
            </Card>
        </Cards>
    </Account>
    <Account>
        <number>2</number>
        <Cards>
            <Card>
                <number>42552</number>
                <type>debit</type>
            </Card>
        </Cards>
    </Account>
</Accounts>
